use sharedtravellerdb;

CREATE TABLE TEMP_PASSWORD (ID int(10) NOT NULL AUTO_INCREMENT, TRAVELLER_ID int(10) NOT NULL, TEMP_PASSWORD varchar(30) NOT NULL, PRIMARY KEY (ID)) ENGINE=InnoDB;

CREATE TABLE REQUEST (
  ID             int(10) NOT NULL AUTO_INCREMENT, 
  TRAVELLER_ID   int(10) NOT NULL, 
  ANNOUNCEMENT_ID int(10) NOT NULL, 
  STATUS         varchar(20) NOT NULL
    CHECK( STATUS IN ('PENDING', 'REJECTED', 'APPROVED', 'DECLINED')), 
  PRIMARY KEY (ID), 
  CONSTRAINT UNIQUE_REQUEST 
    UNIQUE (TRAVELLER_ID, ANNOUNCEMENT_ID)) ENGINE=InnoDB;
    
CREATE TABLE TRAVELLER (
  ID                  int(10) NOT NULL AUTO_INCREMENT, 
  USERNAME            varchar(50) NOT NULL UNIQUE, 
  PASSWORD            varchar(50) NOT NULL, 
  FACEBOOK_AUTH_TOKEN varchar(50), 
  EMAIL               varchar(50) NOT NULL, 
  PHONE_NUMBER        varchar(20) NOT NULL, 
  SMOKER              tinyint(1), 
  FIRST_NAME          varchar(30), 
  LAST_NAME           varchar(30), 
  RATING_COUNT        int(10) DEFAULT 0 CHECK(RATING_COUNT > 0), 
  RATING_SUM          int(10) DEFAULT 0 CHECK(RATING_SUM > 0), 
  TRAVEL_COUNT        int(10),
  EMAIL_NOTIFICATIONS tinyint(1) NOT NULL, 
  SMS_NOTIFICATIONS   tinyint(1) NOT NULL, 
  PRIMARY KEY (ID)) ENGINE=InnoDB;
  
CREATE TABLE NOTIFICATION (
  ID                int(10) NOT NULL AUTO_INCREMENT, 
  CREATION_DATE     datetime NOT NULL, 
  NOTIFICATION_TEXT varchar(1000), 
  SEEN              tinyint(1) DEFAULT 0 NOT NULL, 
  TYPE              varchar(30) NOT NULL, 
  RECEIVER_ID       int(10) NOT NULL, 
  SENDER_ID         int(10) NOT NULL, 
  ANNOUNCEMENT_ID   int(10) NOT NULL, 
  PRIMARY KEY (ID)) ENGINE=InnoDB;
  
CREATE TABLE GENERIC_NOTIFICATION (
  ID       int(10) NOT NULL AUTO_INCREMENT, 
  TYPE     varchar(30) NOT NULL UNIQUE, 
  TEMPLATE varchar(1000) NOT NULL, 
  PRIMARY KEY (ID)) ENGINE=InnoDB;
  
CREATE TABLE INTERMEDIATE_POINT (ANOUNCMENT_ID int(10) NOT NULL, CITY_ID int(10) NOT NULL) ENGINE=InnoDB;

CREATE TABLE VEHICLE (
  ID                  int(10) NOT NULL AUTO_INCREMENT, 
  TRAVELLER_ID        int(10) NOT NULL, 
  DISPLAY_NAME        varchar(30) NOT NULL UNIQUE, 
  MAKE                varchar(30) NOT NULL, 
  MODEL               varchar(30) NOT NULL, 
  YEAR_OF_PRODUCTION  date, 
  REGISTRATION_NUMBER varchar(10), 
  COLOR               varchar(20), 
  SEATS               tinyint, 
  DESCRIPTION         varchar(1000), 
  CCU                 tinyint(1), 
  AIR_BAG             tinyint(1), 
  PRIMARY KEY (ID)) ENGINE=InnoDB;
  
CREATE TABLE COUNTRY (ID int(10) NOT NULL AUTO_INCREMENT, NAME varchar(50) NOT NULL UNIQUE, PRIMARY KEY (ID)) ENGINE=InnoDB;

CREATE TABLE CITY (
  ID         int(10) NOT NULL AUTO_INCREMENT, 
  NAME       varchar(50) NOT NULL UNIQUE, 
  COUNTRY_ID int(10) NOT NULL, 
  PRIMARY KEY (ID), 
  INDEX (ID)) ENGINE=InnoDB;
  
CREATE TABLE ANNOUNCEMENT (
  ID             int(10) NOT NULL AUTO_INCREMENT, 
  START_POINT_ID int(10) NOT NULL, 
  END_POINT_ID   int(10) NOT NULL, 
  ADDRESS        varchar(255), 
  DEPARTURE_DATE date NOT NULL, 
  DEPARTURE_TIME time, 
  VEHICLE_ID     int(10), 
  PRICE          decimal(19, 2), 
  FREE_SEATS     tinyint NOT NULL, 
  STATUS         varchar(20) NOT NULL, 
  DRIVER_ID      int(10) NOT NULL, 
  PRIMARY KEY (ID),
  CONSTRAINT UNIQUE_ANNOUNCEMENT 
    UNIQUE (START_POINT_ID, END_POINT_ID, DEPARTURE_DATE, DRIVER_ID)) ENGINE=InnoDB;
    
ALTER TABLE REQUEST ADD INDEX FKREQUEST857175 (TRAVELLER_ID), 
ADD CONSTRAINT FKREQUEST857175 FOREIGN KEY (TRAVELLER_ID) REFERENCES TRAVELLER (ID);
ALTER TABLE REQUEST ADD INDEX FKREQUEST136053 (ANNOUNCEMENT_ID), 
ADD CONSTRAINT FKREQUEST136053 FOREIGN KEY (ANNOUNCEMENT_ID) REFERENCES ANNOUNCEMENT (ID);

ALTER TABLE NOTIFICATION ADD INDEX announcement (ANNOUNCEMENT_ID), ADD CONSTRAINT announcement FOREIGN KEY (ANNOUNCEMENT_ID) REFERENCES ANNOUNCEMENT (ID);
ALTER TABLE NOTIFICATION ADD INDEX sender (SENDER_ID), ADD CONSTRAINT sender FOREIGN KEY (SENDER_ID) REFERENCES TRAVELLER (ID);
ALTER TABLE NOTIFICATION ADD INDEX receiver (RECEIVER_ID), ADD CONSTRAINT receiver FOREIGN KEY (RECEIVER_ID) REFERENCES TRAVELLER (ID);

ALTER TABLE TEMP_PASSWORD ADD INDEX FKTEMP_PASSW811688 (TRAVELLER_ID), 
ADD CONSTRAINT FKTEMP_PASSW811688 FOREIGN KEY (TRAVELLER_ID) REFERENCES TRAVELLER (ID);

ALTER TABLE INTERMEDIATE_POINT ADD INDEX FKINTERMEDIA367335 (ANOUNCMENT_ID),
ADD CONSTRAINT FKINTERMEDIA367335 FOREIGN KEY (ANOUNCMENT_ID) REFERENCES ANNOUNCEMENT (ID);

ALTER TABLE VEHICLE ADD INDEX FKVEHICLE489754 (TRAVELLER_ID),
ADD CONSTRAINT FKVEHICLE489754 FOREIGN KEY (TRAVELLER_ID) REFERENCES TRAVELLER (ID);

ALTER TABLE ANNOUNCEMENT ADD INDEX FKANNOUNCEME375898 (VEHICLE_ID),
ADD CONSTRAINT FKANNOUNCEME375898 FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (ID);
ALTER TABLE ANNOUNCEMENT ADD INDEX driver (DRIVER_ID), 
ADD CONSTRAINT driver FOREIGN KEY (DRIVER_ID) REFERENCES TRAVELLER (ID);
ALTER TABLE ANNOUNCEMENT ADD INDEX end_point (END_POINT_ID),
ADD CONSTRAINT end_point FOREIGN KEY (END_POINT_ID) REFERENCES CITY (ID);
ALTER TABLE ANNOUNCEMENT ADD INDEX start_point (START_POINT_ID),
ADD CONSTRAINT start_point FOREIGN KEY (START_POINT_ID) REFERENCES CITY (ID);

ALTER TABLE INTERMEDIATE_POINT ADD INDEX FKINTERMEDIA621037 (CITY_ID), 
ADD CONSTRAINT FKINTERMEDIA621037 FOREIGN KEY (CITY_ID) REFERENCES CITY (ID);

ALTER TABLE CITY ADD INDEX FKCITY557241 (COUNTRY_ID), 
ADD CONSTRAINT FKCITY557241 FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID);