CREATE TABLE TEMP_PASSWORD (
  ID            int(10) NOT NULL AUTO_INCREMENT, 
  TRAVELLER_ID  int(10) NOT NULL, 
  TEMP_PASSWORD varchar(30) NOT NULL, 
  PRIMARY KEY (ID)) CHARACTER SET UTF8;
CREATE TABLE NOTIFICATION (
  TRAVELLER_ID  int(10) NOT NULL, 
  ANOUNCMENT_ID int(10) NOT NULL, 
  TYPE          varchar(20) NOT NULL) CHARACTER SET UTF8;
CREATE TABLE TRAVELLER (
  ID                  int(10) NOT NULL AUTO_INCREMENT, 
  USERNAME            varchar(50) NOT NULL, 
  PASSWORD            varchar(50) NOT NULL, 
  FACEBOOK_AUTH_TOKEN varchar(50), 
  EMAIL               varchar(50) NOT NULL, 
  PHONE_NUMBER        varchar(20) NOT NULL, 
  SMOKER              tinyint(1), 
  FIRST_NAME          varchar(30), 
  LAST_NAME           varchar(30), 
  RATING_COUNT        int(10) DEFAULT 0 CHECK(RATING_COUNT > 0), 
  RATING_SUM          int(10) DEFAULT 0 CHECK(RATING_SUM > 0), 
  TRAVEL_COUNT        int(10), 
  PRIMARY KEY (ID)) CHARACTER SET UTF8;
CREATE TABLE INTERMEDIATE_POINT (
  ANOUNCMENT_ID int(10) NOT NULL, 
  CITY_ID       int(10) NOT NULL) CHARACTER SET UTF8;
CREATE TABLE VEHICLE (
  ID                  int(10) NOT NULL AUTO_INCREMENT, 
  TRAVELLER_ID        int(10) NOT NULL, 
  MAKE                varchar(30) NOT NULL, 
  MODEL               varchar(30) NOT NULL, 
  YEAR_OF_PRODUCTION  date, 
  REGISTRATION_NUMNER varchar(10), 
  COLOR               varchar(20), 
  SEATS               tinyint, 
  DESCRIPTION         varchar(1000), 
  CCU                 tinyint(1), 
  AIR_BAG             tinyint(1), 
  PRIMARY KEY (ID)) CHARACTER SET UTF8;
CREATE TABLE COUNTRY (
  ID   int(10) NOT NULL AUTO_INCREMENT, 
  NAME varchar(50) NOT NULL UNIQUE, 
  PRIMARY KEY (ID)) CHARACTER SET UTF8;
CREATE TABLE CITY (
  ID         int(10) NOT NULL AUTO_INCREMENT, 
  NAME       varchar(50) NOT NULL, 
  COUNTRY_ID int(10) NOT NULL, 
  PRIMARY KEY (ID), 
  INDEX (ID)) CHARACTER SET UTF8;
CREATE TABLE ANOUNCMENT (
  ID             int(10) NOT NULL AUTO_INCREMENT, 
  START_POINT_ID int(10) NOT NULL, 
  END_POINT_ID   int(10) NOT NULL, 
  ADDRESS        varchar(255), 
  DEPARTURE_DATE date NOT NULL, 
  DEPARTURE_TIME time, 
  VEHICLE_ID     int(10) NOT NULL, 
  PRICE          decimal(19, 2), 
  FREE_SEATS     tinyint NOT NULL, 
  STATUS         varchar(20) NOT NULL, 
  DRIVER_ID      int(10) NOT NULL, 
  PRIMARY KEY (ID)) CHARACTER SET UTF8;
ALTER TABLE TEMP_PASSWORD ADD INDEX FKTEMP_PASSW811688 (TRAVELLER_ID), ADD CONSTRAINT FKTEMP_PASSW811688 FOREIGN KEY (TRAVELLER_ID) REFERENCES TRAVELLER (ID);
ALTER TABLE INTERMEDIATE_POINT ADD INDEX FKINTERMEDIA923110 (ANOUNCMENT_ID), ADD CONSTRAINT FKINTERMEDIA923110 FOREIGN KEY (ANOUNCMENT_ID) REFERENCES ANOUNCMENT (ID);
ALTER TABLE NOTIFICATION ADD INDEX FKNOTIFICATI472569 (ANOUNCMENT_ID), ADD CONSTRAINT FKNOTIFICATI472569 FOREIGN KEY (ANOUNCMENT_ID) REFERENCES ANOUNCMENT (ID);
ALTER TABLE NOTIFICATION ADD INDEX FKNOTIFICATI17425 (TRAVELLER_ID), ADD CONSTRAINT FKNOTIFICATI17425 FOREIGN KEY (TRAVELLER_ID) REFERENCES TRAVELLER (ID);
ALTER TABLE VEHICLE ADD INDEX FKVEHICLE489754 (TRAVELLER_ID), ADD CONSTRAINT FKVEHICLE489754 FOREIGN KEY (TRAVELLER_ID) REFERENCES TRAVELLER (ID);
ALTER TABLE ANOUNCMENT ADD INDEX FKANOUNCMENT305246 (VEHICLE_ID), ADD CONSTRAINT FKANOUNCMENT305246 FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (ID);
ALTER TABLE ANOUNCMENT ADD INDEX driver (DRIVER_ID), ADD CONSTRAINT driver FOREIGN KEY (DRIVER_ID) REFERENCES TRAVELLER (ID);
ALTER TABLE ANOUNCMENT ADD INDEX end_poin (END_POINT_ID), ADD CONSTRAINT end_poin FOREIGN KEY (END_POINT_ID) REFERENCES CITY (ID);
ALTER TABLE ANOUNCMENT ADD INDEX start_poin (START_POINT_ID), ADD CONSTRAINT start_poin FOREIGN KEY (START_POINT_ID) REFERENCES CITY (ID);
ALTER TABLE INTERMEDIATE_POINT ADD INDEX FKINTERMEDIA621037 (CITY_ID), ADD CONSTRAINT FKINTERMEDIA621037 FOREIGN KEY (CITY_ID) REFERENCES CITY (ID);
ALTER TABLE CITY ADD INDEX FKCITY557241 (COUNTRY_ID), ADD CONSTRAINT FKCITY557241 FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID);
