use sharedtravellerdb;

ALTER TABLE REQUEST DROP FOREIGN KEY FKREQUEST857175;
ALTER TABLE REQUEST DROP FOREIGN KEY FKREQUEST136053;
ALTER TABLE NOTIFICATION DROP FOREIGN KEY announcement;
ALTER TABLE NOTIFICATION DROP FOREIGN KEY sender;
ALTER TABLE NOTIFICATION DROP FOREIGN KEY receiver;
ALTER TABLE TEMP_PASSWORD DROP FOREIGN KEY FKTEMP_PASSW811688;
ALTER TABLE INTERMEDIATE_POINT DROP FOREIGN KEY FKINTERMEDIA367335;
ALTER TABLE VEHICLE DROP FOREIGN KEY FKVEHICLE489754;
ALTER TABLE ANNOUNCEMENT DROP FOREIGN KEY FKANNOUNCEME375898;
ALTER TABLE ANNOUNCEMENT DROP FOREIGN KEY driver;
ALTER TABLE ANNOUNCEMENT DROP FOREIGN KEY start_point;
ALTER TABLE ANNOUNCEMENT DROP FOREIGN KEY end_point;
ALTER TABLE INTERMEDIATE_POINT DROP FOREIGN KEY FKINTERMEDIA621037;
ALTER TABLE CITY DROP FOREIGN KEY FKCITY557241;
DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS TRAVELLER;
DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS GENERIC_NOTIFICATION;
DROP TABLE IF EXISTS TEMP_PASSWORD;
DROP TABLE IF EXISTS INTERMEDIATE_POINT;
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS COUNTRY;
DROP TABLE IF EXISTS CITY;
DROP TABLE IF EXISTS ANNOUNCEMENT;

