use sharedtravellerdb;

INSERT INTO COUNTRY(ID, NAME) VALUES (1, 'BULGARIA');

INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (1, 'Blagoevgrad', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (3, 'Pleven', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (4, 'Sofia', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (5, 'Stara Zagora', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (6, 'Ruse', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (7, 'Bansko', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (8, 'Burgas', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (9, 'Varna', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (10, 'Plovdiv', 1);

INSERT INTO GENERIC_NOTIFICATION(ID, TYPE, TEMPLATE, SINGULAR_TITLE, PLURAL_TITLE)
VALUES(1, 'NEW_REQUEST', '{0}-{1}({2})', 'New request', '{0} new requests');
INSERT INTO GENERIC_NOTIFICATION(ID, TYPE, TEMPLATE, SINGULAR_TITLE)
VALUES(2, 'REQUEST_REJECTION', '{0}-{1}({2})', 'Rejected request');
INSERT INTO GENERIC_NOTIFICATION(ID, TYPE, TEMPLATE, SINGULAR_TITLE)
VALUES(3, 'REQUEST_ACCEPTANCE', '{0}-{1}({2})', 'Approved request');
INSERT INTO GENERIC_NOTIFICATION(ID, TYPE, TEMPLATE, SINGULAR_TITLE, PLURAL_TITLE)
VALUES(4, 'REQUEST_DECLINATION', '{0}-{1}({2})', 'Declined request', '{0} declined requests');
INSERT INTO GENERIC_NOTIFICATION(ID, TYPE, TEMPLATE, SINGULAR_TITTLE)
VALUES(5, 'TRIP_CANCELLATION', '{0}-{1}({2})', 'Trip cancelled');

-- ============================== DUMMY DATA ========================================
INSERT INTO VEHICLE(ID, TRAVELLER_ID, DISPLAY_NAME, MAKE, MODEL, YEAR_OF_PRODUCTION, REGISTRATION_NUMBER, COLOR, SEATS, DESCRIPTION, CCU, AIR_BAG)
VALUES(1, 1, "Audi", "Audi", "A3", '2003-00-00', "E 2030 AS", "green", 5, "very big", false, false),
(2, 1, "OPEL", "OPEL", "Kadet", '1993-00-00', "E 2230 AS", "yellow", 5, "very big", false, false),
(3, 1, "VW", "VW", "Golf", '1997-00-00', "E 2330 AS", "red", 5, "very big", false, false);

INSERT INTO TRAVELLER(ID, USERNAME, PASSWORD, EMAIL, PHONE_NUMBER, SMOKER, FIRST_NAME, LAST_NAME)
VALUES(1, 'temp', 'temp', 'temp@temp.com', '0888888888', 0, 'John', 'Johnson');
