use sharedtravellerdb;

INSERT INTO COUNTRY(ID, NAME) VALUES (1, 'BULGARIA');

INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (1, 'Blagoevgrad', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (3, 'Pleven', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (4, 'Sofia', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (5, 'Stara Zagora', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (6, 'Ruse', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (7, 'Bansko', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (8, 'Burgas', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (9, 'Varna', 1);
INSERT INTO CITY(ID, NAME, COUNTRY_ID) VALUES (10, 'Plovdiv', 1);

INSERT INTO TRAVELLER(ID, USERNAME, PASSWORD, EMAIL, PHONE_NUMBER, SMOKER, FIRST_NAME, LAST_NAME)
VALUES(1, 'temp', 'temp', 'temp@temp.com', '0888888888', 0, 'John', 'Johnson');